language: python
matrix:
    include:
        - python: 3.8
          dist: bionic
        - python: 3.8
          arch: arm64
          dist: bionic 
          
install: pip install flake8 tox-travis

services:
  - postgresql

before_script:
 - psql -c 'create database bitfield;' -U postgres;

script:
- make lint
- make test
deploy:
  provider: pypi
  user: disqus
  password:
    secure: VMFRRlf1r/rIfHiKbPkKafCUCPMqUmwxKXS02COgj38354YiF5wK1IK89FBd+Jeuym3CL+ZXbsHpjGXV16XxGn3QWknlErLFtrkPykGceQczMYPUAaf4STH5/RMpllGZXzsrIu3miW/xa1fpMhZSdVFSPExgmDrVH0TVfO5m7rM=
  on:
    tags: true
